#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyExpenses.Android.Resource", IsApplication=true)]

namespace MyExpenses.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.barColor = global::MyExpenses.Android.Resource.Attribute.barColor;
			global::AndroidHUD.Resource.Attribute.barLength = global::MyExpenses.Android.Resource.Attribute.barLength;
			global::AndroidHUD.Resource.Attribute.barWidth = global::MyExpenses.Android.Resource.Attribute.barWidth;
			global::AndroidHUD.Resource.Attribute.circleColor = global::MyExpenses.Android.Resource.Attribute.circleColor;
			global::AndroidHUD.Resource.Attribute.delayMillis = global::MyExpenses.Android.Resource.Attribute.delayMillis;
			global::AndroidHUD.Resource.Attribute.radius = global::MyExpenses.Android.Resource.Attribute.radius;
			global::AndroidHUD.Resource.Attribute.rimColor = global::MyExpenses.Android.Resource.Attribute.rimColor;
			global::AndroidHUD.Resource.Attribute.rimWidth = global::MyExpenses.Android.Resource.Attribute.rimWidth;
			global::AndroidHUD.Resource.Attribute.spinSpeed = global::MyExpenses.Android.Resource.Attribute.spinSpeed;
			global::AndroidHUD.Resource.Attribute.text = global::MyExpenses.Android.Resource.Attribute.text;
			global::AndroidHUD.Resource.Attribute.textColor = global::MyExpenses.Android.Resource.Attribute.textColor;
			global::AndroidHUD.Resource.Attribute.textSize = global::MyExpenses.Android.Resource.Attribute.textSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::MyExpenses.Android.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::MyExpenses.Android.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::MyExpenses.Android.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::MyExpenses.Android.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::MyExpenses.Android.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::MyExpenses.Android.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::MyExpenses.Android.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::MyExpenses.Android.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::MyExpenses.Android.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::MyExpenses.Android.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::MyExpenses.Android.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::MyExpenses.Android.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::MyExpenses.Android.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_barColor = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_barColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_barLength = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_barLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_barWidth = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_barWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_circleColor = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_circleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_delayMillis = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_delayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_radius = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_radius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_rimColor = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_rimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_rimWidth = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_rimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_spinSpeed = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_spinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_text = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_text;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_textColor = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_textColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_textSize = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_textSize;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::MyExpenses.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::MyExpenses.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int barColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int barLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int barWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int circleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int delayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int radius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int rimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int rimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int spinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int text = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int textColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int textSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int pop = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int standard_padding = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_card = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_new = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_content_save = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_errorstatus = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_successstatus = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int roundedbg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int roundedbgdark = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int billable = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int category = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int date = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int due = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int loadingImage = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int loadingProgressBar = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int loadingProgressWheel = 2131230726;
			
			// aapt resource value: 0x7f080010
			public const int menu_new_expense = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int menu_save_expense = 2131230735;
			
			// aapt resource value: 0x7f080000
			public const int name = 2131230720;
			
			// aapt resource value: 0x7f08000e
			public const int notes = 2131230734;
			
			// aapt resource value: 0x7f080007
			public const int textView1 = 2131230727;
			
			// aapt resource value: 0x7f08000d
			public const int textView2 = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int textView3 = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int textView4 = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int textViewStatus = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int total = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int item_expense = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loading = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingimage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loadingprogress = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int view_expense = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int view_expenses = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu_expense = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int menu_expenses = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int menu_new_expense = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int menu_save_expense = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_barColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_barLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_barWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_circleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_delayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_radius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_rimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_rimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_spinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_text = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_textColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_textSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
